### ISSUE TITLE
Hide text

### ISSUE THREAD

**Issue by benoffi7** [antonKozyriatskyi/CircularProgressIndicator#10]
is there a chance to hide the text in the center? I put a image in the center of the circle but its is ugly this the text behing

Thanks!

**Comment by antonKozyriatskyi** [comment]
Hi! I'm going to add such opportunity in the nearest future. Stay tuned!

**Comment by benoffi7** [comment]
Great! Thanks!

2018-05-30 15:14 GMT-03:00 Anton <notifications@github.com>:

**Comment by benoffi7** [comment]
Great! Thanks very much!
