### ISSUE TITLE
Interpolator

### ISSUE THREAD

**Issue by jemshit** [antonKozyriatskyi/CircularProgressIndicator#19]
Hi, can you add method to change interpolator of animation ? 

This line should take the provided interpolator if exists, default otherwise
https://github.com/antonKozyriatskyi/CircularProgressIndicator/blob/dev/circularprogressindicator/src/main/java/antonkozyriatskyi/circularprogressindicator/CircularProgressIndicator.java#L387

**Comment by jemshit** [comment]
@antonKozyriatskyi Hi, thanks for fixing. Can you publish a new release?

**Comment by antonKozyriatskyi** [comment]
@jemshit sure! I'll make a release by the end of a the day.

**Comment by antonKozyriatskyi** [comment]
@jemshit done! Check out [Setting interpolator](https://github.com/antonKozyriatskyi/CircularProgressIndicator#setting-interpolator) section

**Comment by jemshit** [comment]
@antonKozyriatskyi looks like there is a build error: https://jitpack.io/#antonKozyriatskyi/CircularProgressIndicator

**Comment by antonKozyriatskyi** [comment]
@jemshit I saw. However it seems to work. Can you verify this?

**Comment by jemshit** [comment]
@antonKozyriatskyi `ERROR: Failed to resolve: com.github.antonKozyriatskyi:CircularProgressIndicator:1.3.0`

**Comment by antonKozyriatskyi** [comment]
@jemshit hmm, very weird. I've just check it one more time and it worked. Are you sure you have included JitPack repository? Check out [issue #5](https://github.com/antonKozyriatskyi/CircularProgressIndicator/issues/5).

**Comment by jemshit** [comment]
Yes included, 1.2.2 works fine. Maybe re trigger build at jitpack?

**Comment by antonKozyriatskyi** [comment]
@jemshit I tried several times, but it failed. Though it's successfully building on my machine and I am able to add latest version into all projects I tried. 
Might figure it out later today.

**Comment by antonKozyriatskyi** [comment]
@jemshit can you try again?

**Comment by jemshit** [comment]
Works. Thanks

**Comment by natheeshsunway** [comment]
```allprojects {
    repositories {
        google()
        jcenter()
       **maven { url 'https://jitpack.io' }** 
    }
}```
