### ISSUE TITLE
Cannot set current progress as minutes: seconds

### ISSUE THREAD

**Issue by atumRevluetion** [antonKozyriatskyi/CircularProgressIndicator#29]
i tried to use this library with a countdown timer. How can i format the text which inside of view as format of mm:ss. This is my code 

        val circularProgress = findViewById<CircularProgressIndicator>(R.id.circular_progress)

        circularProgress.maxProgress = 5 * 60000.0
        circularProgress.setCurrentProgress(5 * 60000.0)

        object : CountDownTimer(5 * 60000, 1000) {

            override fun onTick(millisUntilFinished: Long) {
                circularProgress.setCurrentProgress(millisUntilFinished.toDouble())

            }

            override fun onFinish() {
                circularProgress.visibility = View.GONE
            }
        }.start()

**Comment by NmdOfficial** [comment]
You should look at the README file.
You have to use your own patternformat and patternadapter.

**Comment by atumRevluetion** [comment]
thank you
