### ISSUE TITLE
additional unit of progress

### ISSUE THREAD

**Issue by mensarb** [antonKozyriatskyi/CircularProgressIndicator#4]
hi thanks for your library!
is it possible to add a unit to the progress? 
e.g the content of the progress indicator says '25%' instead of '25'

**Comment by antonKozyriatskyi** [comment]
Hi, thanks for the feedback! There's no such option yet, but I'll add it soon, probably by the end of this week.

**Comment by antonKozyriatskyi** [comment]
@mensarb done. Checkout the README for details.

**Comment by mensarb** [comment]
@antonKozyriatskyi thank you!
