### ISSUE TITLE
How to progress clockwise

### ISSUE THREAD

**Issue by liunewshine** [antonKozyriatskyi/CircularProgressIndicator#7]
Current is anticlockwise

**Comment by antonKozyriatskyi** [comment]
Thank you, for the feedback! There's no way to do that now, but I will implement that feature in the future.

**Comment by AhmedX6** [comment]
Ok let us know when it will be done :) Thanks, great library !!

**Comment by antonKozyriatskyi** [comment]
@AhmedX6 thanks, man). I'll try to implement it by the end of this week.

**Comment by antonKozyriatskyi** [comment]
@liunewshine @AhmedX6 done! Use `app:direction` attribute.
